### ISSUE TITLE
Bug: use of a measurement in diff_eq_func doesn't seem to work correctly

### ISSUE THREAD

**Issue by ixjlyons** [moorepants/resonance#127]
1. If you use a measurement in your `diff_eq_func`, you may not need all of the state variables as arguments, which is currently required. It should at least be documented that the function is required to take in all of the state variables. The error is something like `<state_var> not in list` which is a little confusing.

2. Using a measurement inside the `diff_eq_func` doesn't seem to generate the correct result. Example:

```python
from resonance.nonlinear_systems import SingleDoFNonLinearSystem

sys = SingleDoFNonLinearSystem()

sys.constants['m'] = 1
sys.constants['k'] = 100
sys.coordinates['x'] = 1
sys.speeds['v'] = 0

def f(x, k):
    return k * x

sys.add_measurement('spring_force', f)

def rhs(x, v, m, spring_force):
    xdot = v
    vdot = -spring_force / m
    return xdot, vdot

sys.diff_eq_func = rhs
sys.free_response(5).plot(subplots=True)
```
![image](https://user-images.githubusercontent.com/943602/32862926-8d672c36-ca0e-11e7-81a7-5f13cf70adcf.png)

Replacing the use of `spring_force` above with just calling `f` directly generates the correct trajectories, including the measured spring force.

**Comment by moorepants** [comment]
The easiest fix would be to disallow measurements in the rhs function.

This will take some digging...

**Comment by moorepants** [comment]
May have figured this out. The design of `_generate_array_rhs_eval_func` is such that new state values update things properly but the measurements never get updated. Probably a simple fix there.
