### ISSUE TITLE
1. Intro to Jupyter Feedback 

### ISSUE THREAD

**Issue by MicheleShi** [moorepants/resonance#166]
Attached are my comments on notebook 1. Overall, I think this notebook emphasized formatting Markdown cells more than necessary. Formatting a notebook was only really necessary for our final project. Therefore, I think more time should be spent introducing the Python language. I suggested talking about troubleshooting and understanding different types of error messages. It's important to know the different Python object types when deciphering an error message. I also suggested introducing writing loops in Python since loops are very important for the whole course. Finally, one of my concerns was that the notebook needs to be accessible for different institutions, so reference to UC Davis or ENG 122 should be excluded.   

[1_Intro_to_Jupyter_MS.docx](https://github.com/moorepants/resonance/files/1692408/1_Intro_to_Jupyter_MS.docx)

**Comment by moorepants** [comment]
@MicheleShi It is easier if you paste the text from the word doc in the Github text box. Word docs, in general, are a bit difficult to work with in the context of Git, Github, software, etc. Can you edit your above message and paste in the text?

**Comment by moorepants** [comment]
> How much information about Jupyter notebooks, specifically about formatting Markdown cells, do the students actually need to know for this course?

Move to #182 for someone to tackle.

> We weren’t given any introductory information about using the Python language. I know the first homework was meant to be an introduction to Python, but I think it’s beneficial to have in class practice with the language as well.

This was on purpose. The goal was to show just enough Python at each stage in the course so that you theoretically don't need to know any Python up front. As a solution I'd like to improve how we ease students in, as opposed to giving a Python tutorial upfront with everything that is needed. This will hopefully be addressed with #161.

> Need to ensure this book translates well for use at other institutions. E.g. exclude UC Davis login screen, referring to ENG 122.

#183

> Objective 4, “create well-formatted, fully operational notebooks,” was not emphasized for a majority of the course. Only in the project did we need to format our own notebooks.

Yes, we need to improve this. We'd like each homework notebook to be nicely formatted, in addition to the project.

> In “Tour de JupyterHub” Section, include screenshot of Jupyter tab directory. Showing the Jupyter interface may be more important that showing the UC Davis login screen, especially if this book will be used at other institutions.

#183

> Under the “Fetching Notebooks” section, need to revise Step 3 about opening the notebooks. Must state that you need to refresh the list for the fetched notebook to appear.

When this is fixed we can close this issue.

> - Introduction to Python section should include an exercise on writing loops and should define the difference between the types of objects: integer, float, and strings.
> - Introduction to Python section should give some advice on troubleshooting and understanding the error messages (i.e. syntax error, runtime error, and semantic error). I found the Think Python resource helpful.

Moved to #161.
