### ISSUE TITLE
Switch to MIT license (or similar)

### ISSUE THREAD

**Issue by moorepants** [moorepants/resonance#202]
I wrongly believed that CC-BY was functionaly equivalent to MIT/BSD/Apache and licensed this software with CC-BY to handle the code, book, notebooks, etc. all with one license. But it seems that CC-BY is less liberal than MIT/BSD/Apache due to a couple of clauses in the license. See this:

https://opensource.stackexchange.com/questions/9242/why-does-creative-commons-recommend-not-using-cc-by-licenses-for-software

So, I'd like to switch this repository to MIT.

**Comment by moorepants** [comment]
@ixjlyons Do you have any objections to me changing the license for this repo to MIT?

**Comment by ixjlyons** [comment]
No objections from me.

**Comment by moorepants** [comment]
Thanks.
