### ISSUE TITLE
JupyterLab on JupyterHub

### ISSUE THREAD

**Issue by ixjlyons** [moorepants/resonance#26]
It is currently fairly straightforward to enable JupyterLab (see [here](https://github.com/jupyterhub/jupyterhub/issues/690#issuecomment-245606118)) and make it the default page users see when they visit the hub. It does not show any of the nbgrader interface, though, so students wouldn't see where to fetch assignments.

**Comment by moorepants** [comment]
Can we have an an alternative environment?

**Comment by ixjlyons** [comment]
This should now work. The default is the standard interface and the JupyterLab interface is available at `https://<hub-domain>/user/<username>/lab`.

You may need to restart your server (see the control panel). Currently I have the hub configured so I can restart jupyterhub without affecting user servers (it may be better to not have this and instead restart everything after announcing a scheduled downtime).

Setting as the default just involves setting `c.Spawner.default_url = '/lab'` in the jupyterhub config and restarting. It probably shouldn't be made the default without a simple way to access nbgrader's assignment list. I suppose the way to go about this would be to create a [jupyterlab extension](https://jupyterlab-tutorial.readthedocs.io/en/latest/extensions_user.html). A simpler but kinda kludgy way to achieve this would be to generate a simple notebook in the home dir for each user as the user account is created that contains some "welcome information" (link to course website, the assignment list, etc.)

**Comment by moorepants** [comment]
- [ ] See if we can get them to nbgrader somehow.
- [ ] Enabled javascript and understand why it is disabled (security?)

**Comment by ixjlyons** [comment]
It may not be a great idea to have this enabled unless we commit to making it default. I just noticed that I couldn't see any files when I logged in until I went in to the lab interface and shutdown running notebooks.

Also [jupyterlab-hub](https://github.com/jupyterhub/jupyterlab-hub) is a thing and could potentially be used as a template for adding a mechanism to open the nbgrader assignments tab.

**Comment by ZelphirKaltstahl** [comment]
Setting `c.Spawner.default_url = '/lab'` did not work for spawning Docker containers. It seems DockerSpawner does not even care about this setting.
Suggestion: Introduce a separate setting for DockerSpawner.

**Comment by moorepants** [comment]
Closing in favor of #170.
