### ISSUE TITLE
Serve rendered notebooks

### ISSUE THREAD

**Issue by ixjlyons** [moorepants/resonance#34]
Should make sure output is cleared on notebooks before committing them here, then serve the output somewhere else.

- [x] set up CI to run notebooks
- [x] upload rendered notebooks to server and serve them (e.g. bicycle.ucdavis.edu/eng122/notebooks)
- [x] tidy it up

**Comment by moorepants** [comment]
Use doctr for this so they are built on travis.

**Comment by ixjlyons** [comment]
I tried to run the `doctr configure` step but I'm getting a 404 error. I either don't have sufficient permissions to get it started and/or some settings need to be enabled for the repo. @moorepants if you get a chance, could you try to get doctr initialized and then I can start the back-and-forth with travis to get things working properly?

**Comment by ixjlyons** [comment]
For the record, the [`NameError: name '_' is not defined`](https://travis-ci.org/moorepants/resonance#L837) occurring on Travis has [been fixed](https://github.com/jupyter/notebook/commit/daeb0a401bffb6a8b60948b79456c875fd716968) and is in notebook 5.1.0 (released a few days ago and isn't on conda-forge yet). It doesn't currently seem to cause any issues in the output and it should fix itself afaik.

**Comment by ixjlyons** [comment]
Going to run with notebook 5.0.0 for now but working on figuring out what's going on here: https://github.com/jupyter/notebook/issues/2798#issuecomment-330743769

Anyway, I finally got this working and somewhat clean I think. Some stale files from (I'm guessing) the first push from a slightly mis-configured doctr deploy are in `gh_pages` but I think it's alright. Sorry for all the commit noise--everything was working locally so I basically had to play the push, wait 5 minutes, scratch head, push, wait 5 minutes...game for a bit.

Anyway, built notebooks are live: https://moorepants.github.io/resonance

**Comment by ixjlyons** [comment]
So the fix is to add `import notebook.transutils` somewhere before notedown's subclass of `FileContentsManager` is defined (just above where it imports `FileContentsManager` seems to work). Unfortunately that project doesn't look very active--it doesn't actually claim to support notebook 5+.
