### ISSUE TITLE
Notebook 1: Introduction to Jupyter

### ISSUE THREAD

**Issue by moorepants** [moorepants/resonance#38]
- [x] First draft
- [x] Final draft
- [x] Learning Python homework assignment in nbgrader

Topics:
- get on the server
- show how to fetch assignments (need first week's assignment up)
- this notebook can have some nbgrader assignments they can submit
- assignments: import numpy and a python function
- tell what jupyter and python are and why are using them
- jupyter interface/ui, etc
- have them all submit the assignment
- point them to local install instructions

**Comment by ixjlyons** [comment]
Most bases covered with the draft currently up. The intro to python/numpy is real weak though--not entirely sure what/how much to cover. Don't want too much "bottom up."
