### ISSUE TITLE
Issues with matplotlib notebook backend

### ISSUE THREAD

**Issue by ixjlyons** [moorepants/resonance#40]
- I noticed in submitting an assignment through nbgrader that plots don't show up (I think they work with `%matplotlib inline` but need to test)
- The line `>>> trajectories['book_angle'].plot();` in [the book balancing notebook](https://github.com/moorepants/resonance/blob/a235a7ffad49c53ba6e2194f1cdf741e0b7812dc/notebook-src/02-book-balancing-intro.rst) updates the plot above instead of creating a new figure

I've noticed a few other somewhat buggy behaviors compared to `inline`, but can't remember them specifically (iirc similar to the second point above). The animation doesn't appear to work with the `inline` backend at the moment though.

**Comment by moorepants** [comment]
Yes. I noticed the same thing. It is odd. Also the plots don't seem to be showing up after running the execute_notebook.sh script.

**Comment by moorepants** [comment]
I think we've got this mostly working.
