### ISSUE TITLE
Images are marked up with html instead of markdown

### ISSUE THREAD

**Issue by ixjlyons** [moorepants/resonance#54]
Not a huge issue, but it would be helpful at least for the intro to jupyter notebook if images or figures from RST were translated to the `![alt text](path/to/image)` syntax instead of `<img src=...`. Currently thinking for that notebook it might be best to just generate the ipynb, hand tune it, and place it directly in `notebooks/` rather than having it auto-translated.

It also occurred to me I think markdown's handling of image size is a bit limited compared to RST, so that might be why.

**Comment by moorepants** [comment]
Ok, we can adjust as needed. I think after finishing a few notebooks the needed workflow will be clearer.

**Comment by ixjlyons** [comment]
This is fine. We ended up showing them both anyway.
