### ISSUE TITLE
Assignment 2: Book Balance and Bicycle Wheel

### ISSUE THREAD

**Issue by moorepants** [moorepants/resonance#62]
Some topics to address:

- Natural frequency and period of a SDoF linear system
- Working with system objects (adding new measurements, making visualizations)
- Curve fitting a decayed oscillation
- Compound pendulum and the center of percussion
- Maybe a problem on the trifular pendulum from a data perspective (we probably won't cover this in class).

**Comment by moorepants** [comment]
@ixjlyons we don't need to do friction this week, that's next week. Here are some simpler topics. I'll get the bicycle wheel notebook draft up today.

**Comment by ixjlyons** [comment]
Ideas for balancing book problems:

- Introduce Python for loops and have them make a plot (trajectory, maybe period) for various length:thickness ratios.
- Add measurements for the position of the center of mass and plot.

**Comment by moorepants** [comment]
Yes, those are good. In particular have them show that mass doesn't affect the period in this system.

**Comment by moorepants** [comment]
If you can, you could make a system that is a trifular pendulum and tell a bit about it. As a corollary to the other pendulums we used in class.

You can have them create visualizations of the systems we used in class.

Some kind of question that tests whether they understand the concepts of mass/inertia and the forces spring/gravity that make a system move. F=-kx and F = -m*g*l*theta. Identifying and discussing the fundamental sources for vibration in a system.

You could use the center of mass of the book to help them see that for it to be stable it has to stay over the contact point of the book with the cup.

Could have them make an ineractive plot to figure out something.

Could have them fit the simulation of a simplependulum to a compound pendulum's trajectory to find the optimal length that gives the same period, thus finding the center of percussion.

**Comment by moorepants** [comment]
Could make visualizations of the compound bicycle wheel pendulum.
