### ISSUE TITLE
Distributing notebook feedback

### ISSUE THREAD

**Issue by ixjlyons** [moorepants/resonance#74]
Fetching and then uploading feedback HTML files to the LMS is pretty tedious, even for a dozen students. An alternative would be to drop the files in each user's home directory on the server, but the default Jupyter behavior is to edit the file. Need to look into whether or not there's a config option to just view HTML page. If so, write a script to grab the feedback files and put them in each user's home.

**Comment by ixjlyons** [comment]
Not perfect, but you can directly view the page by selecting it via the checkbox and then clicking the view button:

![screenshot_2017-10-06_10-16-39](https://user-images.githubusercontent.com/943602/31289958-9d768f08-aa7f-11e7-8acc-073bcae8898d.png)

**Comment by moorepants** [comment]
That seems like a workable solution. We just have to show them how that works.

**Comment by ixjlyons** [comment]
Ok, I think that's fine. I'm not seeing any Jupyter config stuff for handling how files are opened.

For reference, here's a script for distributing the feedback. Need to look over and test still: http://kristenthyng.com/blog/2016/09/07/jupyterhub+nbgrader/

**Comment by ixjlyons** [comment]
Another question: should we distribute homework solutions? Could use a similar approach to the above script or maybe just upload them to Canvas. Students may be slightly less likely to look at them if they have to download and then upload.

**Comment by ixjlyons** [comment]
The first few grading feedback files were uploaded to Canvas, but we've switched to a script based on the one referenced above that copies the files to students' home directories.

Solutions are being generated from the source notebooks in the homework and are uploaded to Canvas in ipynb and pdf form.
