### ISSUE TITLE
Audit of existing notebooks

### ISSUE THREAD

**Issue by ixjlyons** [moorepants/resonance#8]
### [bicycle2dof](https://github.com/moorepants/eng122/blob/d7683e62af7319f935a5011e45a19f0cfc8e7316/content/materials/notebooks/bicycle2dof.ipynb)

- topics:
    - multi degree of freedom systems
    - turning a system of second order equations of motion into first order in matrix form
    - the eigenvalue problem (in general)
    - phasors
    - mode shapes
    - odeint
    - stability
- needs a sketch of the system with steering and roll state variables
- needs explanation for the two different stiffness matrices
- I think this example would be good for teaching some of the topics listed above, whereas they are currently treated more like dependencies and this is just a real-world example for motivation
- the `benchmark_parameters` could benefit from being a class where you can set attributes rather than a function that returns a dict
- `benchmark_par_to_canonical` should probably be hidden
- the exercises at the end are good, including some exploration and design tasks

### [book_balancing](https://github.com/moorepants/eng122/blob/d7683e62af7319f935a5011e45a19f0cfc8e7316/content/materials/notebooks/book_balancing.ipynb)

- topics:
    - non-linear dynamics
    - linearization
    - Lagrange method
    - odeint
- linearization exercise maybe should be testable in some way
- having them approximate the period of the nonlinear oscillations by looking for zero crossings is nice as a practical exercise
- the real demo up in front of the class went well I think
- the final question (derive the equations of motion) was frustrating to them and may not have been all that enlightening

### [bumpy_road](https://github.com/moorepants/eng122/blob/d7683e62af7319f935a5011e45a19f0cfc8e7316/content/materials/notebooks/bumpy_road.ipynb)

- topics:
    - base excitation
    - homogeneous and particular solution
    - damper design
    - force transmissibility
- needs a drawing (currently refers to book example)
- currently is a bunch of code and a couple design exercise prompts -- need to determine if/how much they should code
- needs significantly more text and equations

### [forced_vibrations_with_viscous_damping](https://github.com/moorepants/eng122/blob/d7683e62af7319f935a5011e45a19f0cfc8e7316/content/materials/notebooks/forced_vibrations_with_viscous_damping.ipynb)

- topics:
    - harmonic excitation (force)
    - homogeneous and particular solution
    - phasors
    - resonance
- this notebook is pretty well fleshed out
- the vector representation section could be the introduction to the topic rather than assuming it's a prereq -- a little phasor widget could be useful here
- there is *a lot* of plotting code here

### [nonlinear_vibrations](https://github.com/moorepants/eng122/blob/d7683e62af7319f935a5011e45a19f0cfc8e7316/content/materials/notebooks/nonlinear_vibrations.ipynb)

- topics:
    - 2nd-order equation of motion to system of first ODEs
    - nonlinear dynamics
    - Coulomb friction
    - pendulum
    - stability (inverted pendulum)
    - comparing linear vs. nonlinear free responses
- this was the first notebook introducing numerical ODE integration
- the intro material of this notebook could be good to just add to the top of the book balancing notebook, since that's a bit more interesting of an example

### [sawtooth_forcing](https://github.com/moorepants/eng122/blob/d7683e62af7319f935a5011e45a19f0cfc8e7316/content/materials/notebooks/sawtooth_forcing_solutions.ipynb)

- topics
    - arbitrary periodic forcing
    - Fourier series
    - symbolic computation
- if used as standalone notebook on Fourier series and periodic forcing, needs more intro material
- when moving to numerical use of the Fourier coefficients, should we use subs on the sympy expressions?
- needs a real-world example
- the concept of using Fourier series coefficients to approximate a complicated forcing function and analytically evaluate the output seems somewhat antiquated -- it's fairly theoretical and I can't come up with a good real-world example

### [vibrating_building](https://github.com/moorepants/eng122/blob/d7683e62af7319f935a5011e45a19f0cfc8e7316/content/materials/notebooks/vibrating_building.ipynb)

- topics:
    - multi-dimensional systems (>2dof)
    - the eigenproblem
    - mode shapes
    - spring only
- needs a diagram/model
- assumes they've already seen the theoretical material -- needs more text and equations
- seems common for students to be lost by all of the matrix manipulations

### [viscous_damping](https://github.com/moorepants/eng122/blob/d7683e62af7319f935a5011e45a19f0cfc8e7316/content/materials/notebooks/viscous_damping.ipynb)

- topics:
    - linear damping
    - under/over/critical damping
- needs a mass-spring-damper diagram
- a motivational real-world example would be cool
- programming of the damping regimes was not great, e.g. hard to choose a c value to make zeta=1

**Comment by moorepants** [comment]
Closing this. We incorparted everything in some modified form. Thanks for laying this out in August.
