### ISSUE TITLE
Distributing solutions

### ISSUE THREAD

**Issue by ixjlyons** [moorepants/resonance#91]
I've totally forgotten about giving out the homework solutions. Should we just convert to PDF and put up on Canvas?

**Comment by moorepants** [comment]
Do they get solutions through nbgrader?

**Comment by ixjlyons** [comment]
No there's basically no way to give them anything back through nbgrader, including feedback and solutions. I'm sure it's not difficult to achieve with an nbgrader extension or just a custom script.

**Comment by moorepants** [comment]
Ok, please output the solutions in whatever you find most appropriate and share on Canvas. Smartsite had a way to tell them the materials are copyrighted as a warning about sharing. If canvas has something like that, let's consider these copyrightable and none shareable outside of class. It'd be nice if the document itself has a copyright stamp on it.

**Comment by ixjlyons** [comment]
Alright I've got a script to append a cell with copyright text at the top and generate a nice PDF with LaTeX in the homework repo. I'll put both the PDF and the notebook file on Canvas.
